test vm: mysql cookbook update
* use mysql2_chef_gem and rm obsolete references to
  mysql::server, mysql::client, mysql::database (they're not supported any more)

* add mysql_service resource to mysql recipe

* mysql cookbook localhost -> 127.0.0.1
This is to address errors like:
ERROR: mysql_databasedbfit had an error: Mysql2::Error: Can't
connect to local MySQL server through socket '/var/lib/mysql/mysql.sock'
(2)

The switch from localhost to 127.0.0.1 was suggested here:
https://github.com/opscode-cookbooks/database/issues/112

* add database_name to the changelog task